name: Deploy auth-service
on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup restservice
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login Docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWD}}
      - name: Build docker image
        run: docker build -t raulmafra/auth-service .
      - name : Push image docker
        run: docker push raulmafra/auth-service
